### ISSUE TITLE
Buttons not working on Unleashed 075 and official 0.103

### ISSUE THREAD

**Issue by Fboesch** [ginkage/FlippAirMouse#24] opened 2024-06-27 12:12 UTC
Hello. I already reported a Bug over at „Unleashed“. I use the Kasiin Module which works fine with 074 Flipper Unleashed Build. Now with the new 075 Build - no AirMouse App version seems to work: As soon the AirMouse App is running, the Cursor is working (via Bluetooth) - but no D-Pad/Back-Button Entry on the Flipper is processed. Hence: to Quit the AirMouse App - i need to Reset Flipper.

Current workaround: I use my Flipper with 074 Release…. MasterX (from Unleashed) asked to open issue here :)

**Comment by ginkage** [comment] 2024-06-27 15:12
I did notice this as well on the official firmware 0.13, so I guess something's changed there. I'll take a look when I have some time.

**Comment by ginkage** [comment] 2024-06-27 22:06
Welp, if anything, I think it's caused by this: https://github.com/flipperdevices/flipperzero-firmware/pull/3675

**Comment by ginkage** [comment] 2024-06-27 22:13
This part:

Missing
- Edge events
- One Shot and other less common flags
- Priorities
- Priority inversion

kinda gives me hope it'll be relatively easy to fix in the future. Not sure what to do now though.

**Comment by ginkage** [comment] 2024-08-15 16:44
Sorry for the long wait, after some PTO I've finally found a fix.

**Comment by ginkage** [comment] 2024-08-15 16:44
Gonna be in your app store once https://github.com/flipperdevices/flipper-application-catalog/pull/454 is merged.

**Closed as completed by ginkage** 2024-08-15 16:44 UTC
